-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-02-22 20:03:48 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



DROP TABLE grupa CASCADE CONSTRAINTS;

DROP TABLE kategorie CASCADE CONSTRAINTS;

DROP TABLE rachunek CASCADE CONSTRAINTS;

DROP TABLE klienci CASCADE CONSTRAINTS;

DROP TABLE pozycjarachunku CASCADE CONSTRAINTS;

DROP TABLE produkty CASCADE CONSTRAINTS;


